### ISSUE TITLE
Runtime error for gamefic and gfk commands

### ISSUE THREAD

**Issue by marcinruszkiewicz** [castwide/gamefic#20]
The error itself:
```
iMac-Administrator:gamefic mruszkiewicz$ gfk test examples/professor/
/Users/mruszkiewicz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/
gamefic-1.0.0/lib/gamefic/shell/command/base.rb:36:in `parser': 
uninitialized constant Slop::Parser (NameError)
```

You do have slop in the gemspec, but I think my error is because I actually have an old version of slop installed for some reason (probably from some legacy code), so since you don't specify the version in the gemspec to be at least 4.x there, it skips it during the installation:

```
iMac-Administrator:gamefic-tests mruszkiewicz$ gem install gamefic-sdk
Done installing documentation for gamefic, sourcemap, concurrent-ruby, sprockets, opal, gamefic-sdk after 15 seconds
6 gems installed
```

You might also want to move this dependency to gamefic itself, since it also blows up with the exact same error in that case and the error actually comes from it:

```
iMac-Administrator:gamefic-tests mruszkiewicz$ gamefic
/Users/mruszkiewicz/.rbenv/versions/2.3.3/gemsets/gamefic/
gems/gamefic-1.0.0/lib/gamefic/shell/command/base.rb:36:in `parser': 
uninitialized constant Slop::Parser (NameError)
```

(edit - added newlines to errors so no need to scroll them and I accidentally a word)

**Comment by castwide** [comment]
Thanks for the report. I moved the slop dependency to gamefic.gemspec and required ~> 4. It's pushed to the repo. I expect to release version 1.1 of both gems in the next couple of days.

**Comment by marcinruszkiewicz** [comment]
Thanks for the fix, I wanted to try it out, so I'll wait to see what you have in store for the next version :)

**Comment by castwide** [comment]
Version 1.1 of Gamefic and the SDK are on RubyGems.

**Comment by castwide** [comment]
Incidentally, I just realized that the commands aren't very user-friendly when they receive unexpected input. A lot of errors result in an exception backtrace. They also don't provide help messages. I created a separate issue #21 to address these problems.

**Comment by marcinruszkiewicz** [comment]
And I can confirm that now the gems are installing slop properly, thanks again for the fix! :)
