### ISSUE TITLE
`exit` from nowhere crashes the game

### ISSUE THREAD

**Issue by Ravenclaw-OIer** [castwide/gamefic#28]
The following interaction says everything.

```
╭─user@host /Users/user/GameName ‹ruby 3.1.2›
╰─$ rake ruby:run

Hello, world!

> exit
rake aborted!
SystemStackError: stack level too deep

Tasks: TOP => ruby:run
(See full trace by running task with --trace)
```

**Comment by castwide** [comment]
Confirmed. I'll get a fix in place for this, but it should be a minor issue in most cases, as it only happens when the player's `room` is `nil`. (In the `gamefic-standard` library, `exit` is a shortcut to leave the current room. If you're trying to exit the game, `quit` should do it.)

**Comment by castwide** [comment]
This issue is fixed in [gamefic-standard](https://github.com/castwide/gamefic-standard) v2.3.1.
